- name: Install nginx
  apt:
    name: nginx-full
    state: present
  register: apt_action
  retries: 10
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
  when: ansible_distribution == 'Ubuntu'
  notify: Restart nginx 


- name: Check is ufw installed
  shell: command -v ufw >/dev/null 2>&1
  register: is_ufw_exist
  ignore_errors: yes
  when: ansible_distribution == 'Ubuntu'


- name: Disabling ufw
  command: ufw disable
  become: yes
  when: ansible_distribution == 'Ubuntu' and is_ufw_exist.rc == 0


- name: load nginx.conf
  template:
    src: "nginx.conf.j2"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Test nginx.conf
  command: "nginx -t"
  register: test
 
